### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Virus18sp** [MaDHouSe79/qb-parking#12]
Will be cool if you can add parking slots limit for vip, so they cant park lot of vehicles just for fun.

**Comment by MaDHouSe79** [comment]
yes i can add this, if you add a vip player you can add the amount if max parking cars. /park-addvip [id] [amount] but this is not working yet, but i'm on it, thank you for your message!

**Comment by Virus18sp** [comment]
Awesome, thanks.
