### ISSUE TITLE
Fuel

### ISSUE THREAD

**Issue by jasini1609** [MaDHouSe79/qb-parking#16]
i have problem with fuel its not saving the fuel state
in qb-garages it works fine 
i use the latest Qbcore 
latest LegacyFuel

**Comment by MaDHouSe79** [comment]
If you have readed the updates.md, you had know, what was wrong with it :P and i'm on it to try to fix this, but LegacyFuel is also a little buggie, and i know the garages works just fine, but i'm doing just the same as the garage do, but if you look good you get a random fuel level every time. and this happend by qb-parking aswell., even if i force a full tank on 3 spots in code, it stil keeps random, and thats sucks. but i'm on it to try to make a fix for it. but it have some delay.
