### ISSUE TITLE
Drive

### ISSUE THREAD

**Issue by jasini1609** [MaDHouSe79/qb-parking#17]
When i park the car with F5 then enter the car and turning it on i can drive away without pressing f5 i can then press f5 anytime to return to that park position.

**Comment by MaDHouSe79** [comment]
i thinkk you turn on your engine, cause thats he only thing whjen i can drive away witout unpark, al other stuff i cant do the same here cause i dont get that, my cars al al parking on spot and i cant drive away, the obly bug now is the engine if you start it you can dirve away. i try to fix that.

**Comment by MaDHouSe79** [comment]
aaa ok, thats the propperties. let my fix this

**Comment by MaDHouSe79** [comment]
can you join my discord? cause that chat a litte easyer and we can fix this issue faster
