### ISSUE TITLE
Cars spawn on top of eachother.

### ISSUE THREAD

**Issue by CptNoHand** [MaDHouSe79/qb-parking#22]
I don't use the premade spots, so players can park where they want. 

And when i park a car or they render in, 3 spawn on top of eachother..

**Comment by MaDHouSe79** [comment]
there is a timer delay in config.lua make it higher if cars spawns like that.

**Comment by CptNoHand** [comment]
i have it on 20k already, but i'll try to go higher

**Comment by MaDHouSe79** [comment]
20k? thats not good... can you say what exacly happends, and when it happends?

**Comment by CptNoHand** [comment]
As soon as i park a car it spawns 2 on top of it, when i park, when i restart the script too, everytime there are 3 cars.

**Comment by MaDHouSe79** [comment]
and if you do Config.RefreshOnPlayerLoad = false in config.lua?

**Comment by CptNoHand** [comment]
i'll try

**Comment by CptNoHand** [comment]
that worked, but now i don't have the keys after restart
