### ISSUE TITLE
Motorcycles disappear

### ISSUE THREAD

**Issue by ApeToe** [MaDHouSe79/qb-parking#23]
After /park'ing a sanchez the vehicle disappears and never returns. Everything looks fine in the database 

![image](https://user-images.githubusercontent.com/2822932/156048061-87e01fd7-47d5-4133-b2d7-4f9f295aa7e6.png)

**Comment by MaDHouSe79** [comment]
is the model correct? cause if this is not the right name than this can happen..

**Comment by MaDHouSe79** [comment]
i hade the same issue with the trailers, cause the model name is trailer but the real model name is trailers so this can be the issue on your end

**Comment by ApeToe** [comment]
Hmm I see how that the model is sachez02, however the vehicle shop is set to sell sanchez2. I wonder where the 0 is coming from?

**Comment by ApeToe** [comment]
Yeah after removing the extra 0 in the sql table it spawned. Double checked the vehicle shop and its sanchez 2. When reparking it does the same thing and doesnt spawn again.

**Comment by MaDHouSe79** [comment]
i added a get a real model name function in to it, the trailers works with that, so hope this wil work for you to.
