### ISSUE TITLE
Keys/Blip

### ISSUE THREAD

**Issue by BrandonSnippets** [MaDHouSe79/qb-parking#24]
Hello MadHouse, I would like to inform you a on a issue. I testing this best of my ability. When a car it parked and server has restarted you dont have keys and the blip is no longer on map. I can unpark the car with third eye. I have to lockpick the car to get in. Once locked picked I can repark the car. 

Have no error client side or server side.

Edit: Also have to hotwire car.

**Comment by MaDHouSe79** [comment]
i have update the code, you have to put extra code to make it work, 
please read the UPDATE.md file what you have to do to make it work again  :)

**Comment by BrandonSnippets** [comment]
> 

Keys are working but blips are still not staying.

**Comment by MaDHouSe79** [comment]
> 

 i update the code again hope it works now :)

**Comment by BrandonSnippets** [comment]
All fixed. Thanks for taking the time to fix them.
