### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WhiskeyFiveOne** [MaDHouSe79/qb-parking#5]
I was wondering if it could be possible to add a feature where other players and steal parked cars even if that player is offline but it will send a notification to all police officers that are in the server on and off duty when the car theft happens. Also have the ability for players to store the stolen vehicle in a garage. Also i would suggest to make it where it can easily be turn on or off if other servers doesn't want that on

**Comment by MaDHouSe79** [comment]
But this is a parking script not a crime script? :D 
and the qb-garages does not have this, this kind of crimes this is done by other script.

This is just a parking script ;).

**Comment by MaDHouSe79** [comment]
.
