### ISSUE TITLE
Lat public park used as impound

### ISSUE THREAD

**Issue by argonaut1972** [MaDHouSe79/qb-parking#7]
Car uses last public parking space as impound.
When using public garage and then taking car out for drive, then logging off, instead of hayes impound receiving car at login, the last public car parking lot is where car appears.
If a garage is used, then car remains in garage, however leaving car out on street results in last public car park receiving car, opposed to impound that should receive car
Not sure if this has been fixed by latest commits, was occurring prior to fixes

**Comment by MaDHouSe79** [comment]
Can you show my the state of that vehicle at that moment in your database? some pic or something? cause i thing qb-garages is doeing this, my parking system sets it only on 3 not 0 1 or 2 i only set the state when unpark or get stolen but i only set the state from 0 to 3 and from 3 back to 0 or the impound trigger must have been called then the state gets in 2 police impound, zo if people buy a car and never put it in a garage 1 time, then you get this. park atleast 1time your vehicle in the garage for qbCore  to save it. cause the qb-garages is doeing a lot of stuf for my already ;)

**Comment by argonaut1972** [comment]
> Can you show my the state of that vehicle at that moment in your database? some pic or something? cause i thing qb-garages is doeing this, my parking system sets it only on 3 not 0 1 or 2 i only set the state when unpark or get stolen but i only set the state from 0 to 3 and from 3 back to 0 or the impound trigger must have been called then the state gets in 2 police impound, zo if people buy a car and never put it in a garage 1 time, then you get this. park atleast 1time your vehicle in the garage for qbCore to save it. cause the qb-garages is doeing a lot of stuf for my already ;)

ok, i used my autarch which has been in s1n_garage (a paid script), then i drove it to hotel parking (from qb-garages), parked it in, then took it out and drove down the road, got out, logged off, logged back in, and the car went back to hotel parking, instead of hayes.
[https://ibb.co/TL8Q5S9](url)
Btw, love this script and your work, hope there's a way to fix this small issue

**Comment by MaDHouSe79** [comment]
change this in your garage config an look what it does after.

AutoRespawn = true --True == auto respawn cars that are outside into your garage on script restart, false == does not put them into your garage and players have to go to the impound

**Comment by argonaut1972** [comment]
> change this in your garage config an look what it does after.
> 
> AutoRespawn = true --True == auto respawn cars that are outside into your garage on script restart, false == does not put them into your garage and players have to go to the impound

ok all fixed ty, keep up the great work, qb-parking is the bees knees, love your work

**Comment by MaDHouSe79** [comment]
yw and thnx you, thats very kind of you 👊😉👍
